--- #YAML:1.0
name:               SDD
version:            0.03
abstract:           Shutdown Daemon
author:
    - Robin Clarke <perl@robinclarke.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:    0
    Getopt::Long:      0
    IPC::Run:          0
    Log::Log4perl:     0
    Params::Validate:  0
    Pod::Usage:        0
    Test::More:        0
    User:              0
    YAML::Any:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
